pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="Version {{version}} ({{date}})"},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n\n## Unreleased\n\nCommits: <https://github.com/aqrln/detect_flake/compare/{{tag_name}}...HEAD>", exactly=1},
]

pre-release-commit-message = "release: {{version}}"
